version: "3.4"

services:

  vdm_training_02_messenger_async:
    container_name: 'vdm_training_02_messenger_async'
    working_dir: '/var/www/html'
    build:
      context: './'
      dockerfile: './Dockerfile'
    command: ["/bin/sh", "-c", "COMPOSER_MEMORY_LIMIT=-1 composer update -n && composer clearcache -n && chmod 777 -R vendor/ composer.lock && sleep 10000000"]
    ports:
      - '5000:80'
    volumes:
      - '.:/var/www/html'
    depends_on:
      - 'vdm_training_02_rabbitmq'

  vdm_training_02_rabbitmq:
    image: rabbitmq:3-management
    container_name: vdm_training_02_rabbitmq
    ports: ["15672:15672"]