framework:
    messenger:
        serializer:
            default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
                format: json
                context:
                    json_encode_options: !php/const JSON_PRESERVE_ZERO_FRACTION

        transports:
            opendatasoft-collect:
                dsn: "vdm+local://%kernel.project_dir%/local/opendatasoft-collect.json?encodeBody=json"
                retry_strategy:
                    max_retries: 0

            opendatasoft-send-to-store:
                dsn: "vdm+local://%kernel.project_dir%/local/opendatasoft-collect-output.json?encodeBody=json"
                retry_strategy:
                    max_retries: 0

        routing:
            App\Message\OpenDataSoftStoreMessage: opendatasoft-send-to-store
